clone_depth: 50
skip_tags: true
version: 4.1.{build}
environment:

  APPVEYOR_PYTHON_URL: "https://raw.githubusercontent.com/dvorapa/python-appveyor-demo/master/appveyor/"

  # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
  # /E:ON and /V:ON options are not enabled in the batch script interpreter
  # See: http://stackoverflow.com/a/13751649/163740
  CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  PYWIKIBOT_DIR: "%appdata%\\Pywikibot"
  PYWIKIBOT_USER_CONFIG: "%appdata%\\Pywikibot\\user-config.py"
  PYWIKIBOT_PASSWD_FILE: "%appdata%\\Pywikibot\\passwordfile"

  PYSETUP_TEST_EXTRAS: "1"
  PYSETUP_TEST_NO_UI: "1"
  PYWIKIBOT_NO_L10N_TESTS: "1"
  PYWIKIBOT_TESTS_RUNNING: "1"

  matrix:

    # Test the lowest supported release of each major Python version

    - PYTHON: "C:\\Python350-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"

    # Appveyor pre-installs these versions onto build machines

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "64"

matrix:
  fast_finish: false

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

install:
  - git submodule update --init
  # Download the Appveyor Python build accessories into subdirectory .\appveyor
  - mkdir appveyor
  - ps: $wc = new-object net.webclient
  - ps: $run = $wc.DownloadString($env:APPVEYOR_PYTHON_URL + 'run_with_env.cmd')
  - ps: $run | Out-File -Encoding ascii -FilePath appveyor\run_with_env.cmd

  # This is needed for Python versions not installed on Appveyor build machines
  - ps: |
      if (-not(Test-Path($env:PYTHON))) {
        iex $wc.DownloadString($env:APPVEYOR_PYTHON_URL + 'install.ps1')
      }
  - pip install virtualenv
  - virtualenv env
  - env\Scripts\activate.bat
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt

build: off

test_script:
  - chcp 65001
  - set PYTHONIOENCODING=utf8
  - set PYTHONWARNINGS=ignore:::pkg_resources.py2_warn

  - "mkdir %PYWIKIBOT_DIR%"
  - "python -Werror::UserWarning -m generate_user_files -dir:%PYWIKIBOT_DIR% -family:wikipedia -lang:en -v -debug -user:%PYWIKIBOT_USERNAME%"
  - ps: "[IO.File]::AppendAllText($env:PYWIKIBOT_USER_CONFIG, 'max_retries = 2; maximum_GET_length = 5000; transliteration_target = None;')"
  - ps: "[IO.File]::AppendAllText($env:PYWIKIBOT_USER_CONFIG, 'usernames[''wikipedia''][''test''] = ''{0}'';' -f $env:PYWIKIBOT_USERNAME)"
  - ps: "[IO.File]::AppendAllText($env:PYWIKIBOT_USER_CONFIG, 'usernames[''wikidata''][''test''] = ''{0}'';' -f $env:PYWIKIBOT_USERNAME)"
  - ps: "[IO.File]::AppendAllText($env:PYWIKIBOT_USER_CONFIG, 'usernames[''commons''][''commons''] = ''{0}'';' -f $env:PYWIKIBOT_USERNAME)"
  - ps: "[IO.File]::AppendAllText($env:PYWIKIBOT_USER_CONFIG, 'usernames[''meta''][''meta''] = ''{0}'';' -f $env:PYWIKIBOT_USERNAME)"
  - ps: "[IO.File]::AppendAllText($env:PYWIKIBOT_USER_CONFIG, 'usernames[''wikisource''][''zh''] = ''{0}'';' -f $env:PYWIKIBOT_USERNAME)"
  - ps: "[IO.File]::AppendAllText($env:PYWIKIBOT_PASSWD_FILE, ('(''{0}'', ''{1}'')\n' -f $env:PYWIKIBOT_USERNAME, $env:USER_PASSWORD))"
  - ps: "[IO.File]::AppendAllText($env:PYWIKIBOT_USER_CONFIG, 'password_file = ''{0}'';' -f $env:PYWIKIBOT_PASSWD_FILE.replace('\\', '\\\\'))"

  - "%CMD_IN_ENV% coverage run -m unittest discover -vv -p \"*_tests.py\""

on_finish:
  - codecov

artifacts:
  - path: dist\*  .coverage coverage.xml
